name: localgraph
description: mobile implemenation of the user specific kgraph
version: 0.0.1
homepage: https://mytiki.com
repository: https://github.com/tiki/localgraph
issue_tracker: https://github.com/tiki/localgraph/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  sqflite_sqlcipher: ^2.1.0
  collection: ^1.15.0
  wallet:
    git:
      url: https://github.com/tiki/wallet
      ref: 0.0.10
  localchain:
    git:
      url: https://github.com/tiki/localchain
      ref: 0.0.2
  httpp:
    git:
      url: https://github.com/tiki/httpp
      ref: 0.0.3

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

dev_dependencies:
  flutter_test:
    sdk: flutter
